d

diff --git a/java/17/Dockerfile b/java/17/Dockerfile
--- a/java/17/Dockerfile
+++ b/java/17/Dockerfile
@@ -35,6 +35,15 @@ USER        container
 ENV         USER=container HOME=/home/container
 WORKDIR     /home/container
 
-COPY        ../entrypoint.sh /entrypoint.sh
+COPY        ./../entrypoint.sh /entrypoint.sh
+
+# Copy server.jar into the container
+COPY        ./../server.jar /home/container/server.jar
+
+# Check server.jar size
+RUN if [ "$(stat -c %s /home/container/server.jar)" -lt 1048576 ]; then \
+        echo "Error: server.jar size is less than 1MB. Please ensure the server.jar file has a minimum size of 1MB." >&2; \
+        exit 1; \
+    fi
 
 CMD         [ "/bin/bash", "/entrypoint.sh" ]
